# This workflow pulls the latest version of AsyncAPI Generator and the template
name: Build Image with AsyncAPI Generator and SCS Template

on: push

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image and save to .tar
        run: |
          mkdir build
          docker build . -t scs-gen:latest
          docker save scs-gen:latest | gzip > ./build/scs-gen.tar.gz

      # https://github.com/marketplace/actions/automatic-releases
      - name: Create release and attach binary as asset
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            ./build/scs-gen.tar.gz
