# This workflow pulls the latest version of AsyncAPI Generator and the template
name: Build Image with AsyncAPI Generator and SCS Template

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image and save to .tar
        run: |
          mkdir build
          docker build . -t scs-gen:latest
          docker save scs-gen:latest | gzip > ./build/scs-gen.tar.gz

      # https://github.com/marketplace/actions/github-releases
      - name: Create release and attach binary as asset
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: build/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
